export { default as authRouter } from './auth/auth.route'
export { default as userRouter } from './user/user.route'
export { companyRouter } from './companies/company.route'
// export { default as searchRouter } from './searches/search.routes'
export { default as resumeRouter } from './resumes/resume.route'
export { default as jobRouter } from './jobs/job.route'
export { default as skillRouter } from './skills/skill.route'
export { default as categoryRouter } from './categories/category.route'
export { default as savedJobRouter } from './saved-jobs/saved-job.route'
export { default as applicationRouter } from './applications/application.route'
export { default as connectionInterestRouter } from './connection-interests/connection-interest.route'
export { default as locationRouter } from './locations/location.route'
